// Generated by tools/pattern-atlas/export-collection.mjs.
// Generator seeds, authored placements, and solver implementation stay private.
export const COLLECTION = {
  "id": "collection-01",
  "title": "The First Atlas",
  "version": 2,
  "levels": [
    {
      "id": "study-01",
      "number": "Study 01",
      "title": "First light",
      "chapter": "Trace",
      "difficulty": "Gentle",
      "size": 3,
      "mode": "target",
      "target": [
        [
          "coral",
          "blue",
          "lime"
        ],
        [
          "lime",
          "violet",
          "orange"
        ],
        [
          "orange",
          "teal",
          "coral"
        ]
      ],
      "pieces": [
        {
          "id": "piece-2",
          "cells": [
            [
              1,
              0,
              "lime"
            ],
            [
              1,
              1,
              "orange"
            ],
            [
              0,
              2,
              "teal"
            ],
            [
              1,
              2,
              "coral"
            ]
          ],
          "rotation": 0,
          "allowedRotations": [
            0,
            1,
            2,
            3
          ]
        },
        {
          "id": "piece-3",
          "cells": [
            [
              0,
              0,
              "lime"
            ],
            [
              0,
              1,
              "orange"
            ]
          ],
          "rotation": 0,
          "allowedRotations": [
            0,
            1,
            2,
            3
          ]
        },
        {
          "id": "piece-1",
          "cells": [
            [
              0,
              0,
              "coral"
            ],
            [
              1,
              0,
              "blue"
            ],
            [
              1,
              1,
              "violet"
            ]
          ],
          "rotation": 1,
          "allowedRotations": [
            0,
            1,
            2,
            3
          ]
        }
      ]
    },
    {
      "id": "study-02",
      "number": "Study 02",
      "title": "Crosswind",
      "chapter": "Trace",
      "difficulty": "Gentle",
      "size": 3,
      "mode": "target",
      "target": [
        [
          "blue",
          "lime",
          "violet"
        ],
        [
          "violet",
          "orange",
          "teal"
        ],
        [
          "teal",
          "coral",
          "blue"
        ]
      ],
      "pieces": [
        {
          "id": "piece-4",
          "cells": [
            [
              0,
              0,
              "teal"
            ],
            [
              0,
              1,
              "blue"
            ]
          ],
          "rotation": 0,
          "allowedRotations": [
            0,
            1,
            2,
            3
          ]
        },
        {
          "id": "piece-3",
          "cells": [
            [
              1,
              0,
              "orange"
            ],
            [
              0,
              1,
              "teal"
            ],
            [
              1,
              1,
              "coral"
            ]
          ],
          "rotation": 0,
          "allowedRotations": [
            0,
            1,
            2,
            3
          ]
        },
        {
          "id": "piece-2",
          "cells": [
            [
              0,
              0,
              "lime"
            ],
            [
              1,
              0,
              "violet"
            ]
          ],
          "rotation": 0,
          "allowedRotations": [
            0,
            1,
            2,
            3
          ]
        },
        {
          "id": "piece-1",
          "cells": [
            [
              0,
              0,
              "blue"
            ],
            [
              0,
              1,
              "violet"
            ]
          ],
          "rotation": 2,
          "allowedRotations": [
            0,
            1,
            2,
            3
          ]
        }
      ]
    },
    {
      "id": "study-03",
      "number": "Study 03",
      "title": "Echo tiles",
      "chapter": "Trace",
      "difficulty": "Focus",
      "size": 4,
      "mode": "target",
      "target": [
        [
          "lime",
          "violet",
          "orange",
          "teal"
        ],
        [
          "orange",
          "teal",
          "coral",
          "blue"
        ],
        [
          "coral",
          "blue",
          "lime",
          "violet"
        ],
        [
          "lime",
          "violet",
          "orange",
          "teal"
        ]
      ],
      "pieces": [
        {
          "id": "piece-4",
          "cells": [
            [
              1,
              0,
              "lime"
            ],
            [
              0,
              1,
              "violet"
            ],
            [
              1,
              1,
              "orange"
            ]
          ],
          "rotation": 0,
          "allowedRotations": [
            0,
            1,
            2,
            3
          ]
        },
        {
          "id": "piece-1",
          "cells": [
            [
              0,
              0,
              "lime"
            ],
            [
              0,
              1,
              "orange"
            ],
            [
              1,
              1,
              "teal"
            ],
            [
              0,
              2,
              "coral"
            ],
            [
              1,
              2,
              "blue"
            ],
            [
              0,
              3,
              "lime"
            ]
          ],
          "rotation": 3,
          "allowedRotations": [
            0,
            1,
            2,
            3
          ]
        },
        {
          "id": "piece-2",
          "cells": [
            [
              0,
              0,
              "violet"
            ],
            [
              1,
              0,
              "orange"
            ],
            [
              2,
              0,
              "teal"
            ]
          ],
          "rotation": 0,
          "allowedRotations": [
            0,
            1,
            2,
            3
          ]
        },
        {
          "id": "piece-3",
          "cells": [
            [
              0,
              0,
              "coral"
            ],
            [
              1,
              0,
              "blue"
            ],
            [
              1,
              1,
              "violet"
            ],
            [
              1,
              2,
              "teal"
            ]
          ],
          "rotation": 0,
          "allowedRotations": [
            0,
            1,
            2,
            3
          ]
        }
      ]
    },
    {
      "id": "study-04",
      "number": "Study 04",
      "title": "Blue hour",
      "chapter": "Trace",
      "difficulty": "Focus",
      "size": 4,
      "mode": "target",
      "target": [
        [
          "violet",
          "orange",
          "teal",
          "coral"
        ],
        [
          "teal",
          "coral",
          "blue",
          "lime"
        ],
        [
          "blue",
          "lime",
          "violet",
          "orange"
        ],
        [
          "violet",
          "orange",
          "teal",
          "coral"
        ]
      ],
      "pieces": [
        {
          "id": "piece-5",
          "cells": [
            [
              0,
              0,
              "violet"
            ],
            [
              1,
              0,
              "orange"
            ]
          ],
          "rotation": 0,
          "allowedRotations": [
            0,
            1,
            2,
            3
          ]
        },
        {
          "id": "piece-4",
          "cells": [
            [
              0,
              0,
              "violet"
            ],
            [
              1,
              0,
              "orange"
            ],
            [
              0,
              1,
              "teal"
            ],
            [
              1,
              1,
              "coral"
            ]
          ],
          "rotation": 0,
          "allowedRotations": [
            0,
            1,
            2,
            3
          ]
        },
        {
          "id": "piece-3",
          "cells": [
            [
              1,
              0,
              "coral"
            ],
            [
              0,
              1,
              "blue"
            ],
            [
              1,
              1,
              "lime"
            ]
          ],
          "rotation": 0,
          "allowedRotations": [
            0,
            1,
            2,
            3
          ]
        },
        {
          "id": "piece-2",
          "cells": [
            [
              0,
              0,
              "orange"
            ],
            [
              1,
              0,
              "teal"
            ],
            [
              0,
              1,
              "coral"
            ]
          ],
          "rotation": 0,
          "allowedRotations": [
            0,
            1,
            2,
            3
          ]
        },
        {
          "id": "piece-1",
          "cells": [
            [
              0,
              0,
              "violet"
            ],
            [
              0,
              1,
              "teal"
            ],
            [
              0,
              2,
              "blue"
            ],
            [
              1,
              2,
              "lime"
            ]
          ],
          "rotation": 1,
          "allowedRotations": [
            0,
            1,
            2,
            3
          ]
        }
      ]
    },
    {
      "id": "study-05",
      "number": "Study 05",
      "title": "Turning point",
      "chapter": "Turn",
      "difficulty": "Turn",
      "size": 4,
      "mode": "target",
      "target": [
        [
          "orange",
          "coral",
          "lime",
          "orange"
        ],
        [
          "blue",
          "violet",
          "teal",
          "blue"
        ],
        [
          "orange",
          "coral",
          "lime",
          "orange"
        ],
        [
          "blue",
          "violet",
          "teal",
          "blue"
        ]
      ],
      "pieces": [
        {
          "id": "piece-2",
          "cells": [
            [
              0,
              0,
              "coral"
            ],
            [
              0,
              1,
              "violet"
            ],
            [
              1,
              1,
              "teal"
            ]
          ],
          "rotation": 3,
          "allowedRotations": [
            0,
            1,
            2,
            3
          ]
        },
        {
          "id": "piece-3",
          "cells": [
            [
              0,
              0,
              "lime"
            ],
            [
              1,
              0,
              "orange"
            ]
          ],
          "rotation": 0,
          "allowedRotations": [
            0,
            1,
            2,
            3
          ]
        },
        {
          "id": "piece-4",
          "cells": [
            [
              1,
              0,
              "blue"
            ],
            [
              0,
              1,
              "lime"
            ],
            [
              1,
              1,
              "orange"
            ],
            [
              0,
              2,
              "teal"
            ],
            [
              1,
              2,
              "blue"
            ]
          ],
          "rotation": 0,
          "allowedRotations": [
            0,
            1,
            2,
            3
          ]
        },
        {
          "id": "piece-5",
          "cells": [
            [
              0,
              0,
              "orange"
            ],
            [
              1,
              0,
              "coral"
            ]
          ],
          "rotation": 0,
          "allowedRotations": [
            0,
            1,
            2,
            3
          ]
        },
        {
          "id": "piece-6",
          "cells": [
            [
              0,
              0,
              "blue"
            ],
            [
              1,
              0,
              "violet"
            ]
          ],
          "rotation": 0,
          "allowedRotations": [
            0,
            1,
            2,
            3
          ]
        },
        {
          "id": "piece-1",
          "cells": [
            [
              0,
              0,
              "orange"
            ],
            [
              0,
              1,
              "blue"
            ]
          ],
          "rotation": 2,
          "allowedRotations": [
            0,
            1,
            2,
            3
          ]
        }
      ]
    },
    {
      "id": "study-06",
      "number": "Study 06",
      "title": "Counterweight",
      "chapter": "Turn",
      "difficulty": "Turn",
      "size": 5,
      "mode": "target",
      "target": [
        [
          "teal",
          "blue",
          "violet",
          "teal",
          "blue"
        ],
        [
          "lime",
          "orange",
          "coral",
          "lime",
          "orange"
        ],
        [
          "teal",
          "blue",
          "violet",
          "teal",
          "blue"
        ],
        [
          "lime",
          "orange",
          "coral",
          "lime",
          "orange"
        ],
        [
          "teal",
          "blue",
          "violet",
          "teal",
          "blue"
        ]
      ],
      "pieces": [
        {
          "id": "piece-4",
          "cells": [
            [
              0,
              0,
              "teal"
            ],
            [
              0,
              1,
              "lime"
            ],
            [
              0,
              2,
              "teal"
            ]
          ],
          "rotation": 0,
          "allowedRotations": [
            0,
            1,
            2,
            3
          ]
        },
        {
          "id": "piece-3",
          "cells": [
            [
              3,
              0,
              "orange"
            ],
            [
              2,
              1,
              "teal"
            ],
            [
              3,
              1,
              "blue"
            ],
            [
              0,
              2,
              "orange"
            ],
            [
              1,
              2,
              "coral"
            ],
            [
              2,
              2,
              "lime"
            ],
            [
              3,
              2,
              "orange"
            ]
          ],
          "rotation": 0,
          "allowedRotations": [
            0,
            1,
            2,
            3
          ]
        },
        {
          "id": "piece-2",
          "cells": [
            [
              0,
              0,
              "orange"
            ],
            [
              1,
              0,
              "coral"
            ],
            [
              0,
              1,
              "blue"
            ],
            [
              1,
              1,
              "violet"
            ]
          ],
          "rotation": 1,
          "allowedRotations": [
            0,
            1,
            2,
            3
          ]
        },
        {
          "id": "piece-1",
          "cells": [
            [
              0,
              0,
              "teal"
            ],
            [
              1,
              0,
              "blue"
            ],
            [
              2,
              0,
              "violet"
            ],
            [
              3,
              0,
              "teal"
            ],
            [
              4,
              0,
              "blue"
            ],
            [
              0,
              1,
              "lime"
            ],
            [
              3,
              1,
              "lime"
            ]
          ],
          "rotation": 3,
          "allowedRotations": [
            0,
            1,
            2,
            3
          ]
        },
        {
          "id": "piece-6",
          "cells": [
            [
              0,
              0,
              "teal"
            ],
            [
              1,
              0,
              "blue"
            ]
          ],
          "rotation": 0,
          "allowedRotations": [
            0,
            1,
            2,
            3
          ]
        },
        {
          "id": "piece-5",
          "cells": [
            [
              0,
              0,
              "blue"
            ],
            [
              1,
              0,
              "violet"
            ]
          ],
          "rotation": 0,
          "allowedRotations": [
            0,
            1,
            2,
            3
          ]
        }
      ]
    },
    {
      "id": "study-07",
      "number": "Study 07",
      "title": "False symmetry",
      "chapter": "Turn",
      "difficulty": "Turn",
      "size": 5,
      "mode": "target",
      "target": [
        [
          "coral",
          "lime",
          "orange",
          "coral",
          "lime"
        ],
        [
          "violet",
          "teal",
          "blue",
          "violet",
          "teal"
        ],
        [
          "coral",
          "lime",
          "orange",
          "coral",
          "lime"
        ],
        [
          "violet",
          "teal",
          "blue",
          "violet",
          "teal"
        ],
        [
          "coral",
          "lime",
          "orange",
          "coral",
          "lime"
        ]
      ],
      "pieces": [
        {
          "id": "piece-6",
          "cells": [
            [
              1,
              0,
              "teal"
            ],
            [
              0,
              1,
              "coral"
            ],
            [
              1,
              1,
              "lime"
            ]
          ],
          "rotation": 0,
          "allowedRotations": [
            0,
            1,
            2,
            3
          ]
        },
        {
          "id": "piece-7",
          "cells": [
            [
              0,
              0,
              "lime"
            ],
            [
              1,
              0,
              "orange"
            ]
          ],
          "rotation": 0,
          "allowedRotations": [
            0,
            1,
            2,
            3
          ]
        },
        {
          "id": "piece-1",
          "cells": [
            [
              0,
              0,
              "coral"
            ],
            [
              0,
              1,
              "violet"
            ],
            [
              0,
              2,
              "coral"
            ]
          ],
          "rotation": 1,
          "allowedRotations": [
            0,
            1,
            2,
            3
          ]
        },
        {
          "id": "piece-2",
          "cells": [
            [
              0,
              0,
              "lime"
            ],
            [
              1,
              0,
              "orange"
            ],
            [
              0,
              1,
              "teal"
            ],
            [
              0,
              2,
              "lime"
            ]
          ],
          "rotation": 2,
          "allowedRotations": [
            0,
            1,
            2,
            3
          ]
        },
        {
          "id": "piece-3",
          "cells": [
            [
              0,
              0,
              "coral"
            ],
            [
              1,
              0,
              "lime"
            ],
            [
              1,
              1,
              "teal"
            ]
          ],
          "rotation": 0,
          "allowedRotations": [
            0,
            1,
            2,
            3
          ]
        },
        {
          "id": "piece-4",
          "cells": [
            [
              0,
              0,
              "blue"
            ],
            [
              1,
              0,
              "violet"
            ],
            [
              1,
              1,
              "coral"
            ],
            [
              2,
              1,
              "lime"
            ],
            [
              1,
              2,
              "violet"
            ]
          ],
          "rotation": 0,
          "allowedRotations": [
            0,
            1,
            2,
            3
          ]
        },
        {
          "id": "piece-5",
          "cells": [
            [
              2,
              0,
              "orange"
            ],
            [
              0,
              1,
              "violet"
            ],
            [
              1,
              1,
              "teal"
            ],
            [
              2,
              1,
              "blue"
            ],
            [
              0,
              2,
              "coral"
            ]
          ],
          "rotation": 0,
          "allowedRotations": [
            0,
            1,
            2,
            3
          ]
        }
      ]
    },
    {
      "id": "study-08",
      "number": "Study 08",
      "title": "Four directions",
      "chapter": "Turn",
      "difficulty": "Turn",
      "size": 5,
      "mode": "target",
      "target": [
        [
          "blue",
          "violet",
          "teal",
          "blue",
          "violet"
        ],
        [
          "orange",
          "coral",
          "lime",
          "orange",
          "coral"
        ],
        [
          "blue",
          "violet",
          "teal",
          "blue",
          "violet"
        ],
        [
          "orange",
          "coral",
          "lime",
          "orange",
          "coral"
        ],
        [
          "blue",
          "violet",
          "teal",
          "blue",
          "violet"
        ]
      ],
      "pieces": [
        {
          "id": "piece-6",
          "cells": [
            [
              0,
              0,
              "orange"
            ],
            [
              0,
              1,
              "blue"
            ]
          ],
          "rotation": 0,
          "allowedRotations": [
            0,
            1,
            2,
            3
          ]
        },
        {
          "id": "piece-5",
          "cells": [
            [
              1,
              0,
              "blue"
            ],
            [
              0,
              1,
              "lime"
            ],
            [
              1,
              1,
              "orange"
            ],
            [
              2,
              1,
              "coral"
            ]
          ],
          "rotation": 0,
          "allowedRotations": [
            0,
            1,
            2,
            3
          ]
        },
        {
          "id": "piece-4",
          "cells": [
            [
              0,
              0,
              "orange"
            ],
            [
              1,
              0,
              "coral"
            ],
            [
              1,
              1,
              "violet"
            ]
          ],
          "rotation": 0,
          "allowedRotations": [
            0,
            1,
            2,
            3
          ]
        },
        {
          "id": "piece-3",
          "cells": [
            [
              0,
              0,
              "teal"
            ],
            [
              1,
              0,
              "blue"
            ],
            [
              2,
              0,
              "violet"
            ]
          ],
          "rotation": 0,
          "allowedRotations": [
            0,
            1,
            2,
            3
          ]
        },
        {
          "id": "piece-2",
          "cells": [
            [
              0,
              0,
              "violet"
            ],
            [
              0,
              1,
              "coral"
            ],
            [
              1,
              1,
              "lime"
            ]
          ],
          "rotation": 3,
          "allowedRotations": [
            0,
            1,
            2,
            3
          ]
        },
        {
          "id": "piece-1",
          "cells": [
            [
              0,
              0,
              "blue"
            ],
            [
              0,
              1,
              "orange"
            ],
            [
              0,
              2,
              "blue"
            ],
            [
              1,
              2,
              "violet"
            ],
            [
              2,
              2,
              "teal"
            ]
          ],
          "rotation": 2,
          "allowedRotations": [
            0,
            1,
            2,
            3
          ]
        },
        {
          "id": "piece-8",
          "cells": [
            [
              0,
              0,
              "blue"
            ],
            [
              1,
              0,
              "violet"
            ]
          ],
          "rotation": 0,
          "allowedRotations": [
            0,
            1,
            2,
            3
          ]
        },
        {
          "id": "piece-7",
          "cells": [
            [
              0,
              0,
              "coral"
            ],
            [
              0,
              1,
              "violet"
            ],
            [
              1,
              1,
              "teal"
            ]
          ],
          "rotation": 0,
          "allowedRotations": [
            0,
            1,
            2,
            3
          ]
        }
      ]
    },
    {
      "id": "study-09",
      "number": "Study 09",
      "title": "Signal garden",
      "chapter": "Veil",
      "difficulty": "Inference",
      "size": 5,
      "mode": "clues",
      "target": [
        [
          "lime",
          "violet",
          "orange",
          "teal",
          "coral"
        ],
        [
          "violet",
          "orange",
          "teal",
          "coral",
          "blue"
        ],
        [
          "orange",
          "teal",
          "coral",
          "blue",
          "lime"
        ],
        [
          "teal",
          "coral",
          "blue",
          "lime",
          "violet"
        ],
        [
          "coral",
          "blue",
          "lime",
          "violet",
          "orange"
        ]
      ],
      "clues": [
        [
          0,
          0
        ],
        [
          1,
          0
        ],
        [
          0,
          1
        ],
        [
          4,
          1
        ],
        [
          3,
          2
        ],
        [
          4,
          2
        ],
        [
          1,
          3
        ],
        [
          2,
          3
        ],
        [
          0,
          4
        ],
        [
          1,
          4
        ]
      ],
      "pieces": [
        {
          "id": "piece-5",
          "cells": [
            [
              0,
              0,
              "blue"
            ],
            [
              0,
              1,
              "lime"
            ]
          ],
          "rotation": 0,
          "allowedRotations": [
            0,
            1,
            2,
            3
          ]
        },
        {
          "id": "piece-6",
          "cells": [
            [
              1,
              0,
              "blue"
            ],
            [
              0,
              1,
              "blue"
            ],
            [
              1,
              1,
              "lime"
            ],
            [
              2,
              1,
              "violet"
            ],
            [
              2,
              2,
              "orange"
            ]
          ],
          "rotation": 0,
          "allowedRotations": [
            0,
            1,
            2,
            3
          ]
        },
        {
          "id": "piece-7",
          "cells": [
            [
              1,
              0,
              "coral"
            ],
            [
              0,
              1,
              "coral"
            ],
            [
              1,
              1,
              "blue"
            ],
            [
              2,
              1,
              "lime"
            ],
            [
              3,
              1,
              "violet"
            ]
          ],
          "rotation": 0,
          "allowedRotations": [
            0,
            1,
            2,
            3
          ]
        },
        {
          "id": "piece-1",
          "cells": [
            [
              0,
              0,
              "lime"
            ],
            [
              0,
              1,
              "violet"
            ]
          ],
          "rotation": 3,
          "allowedRotations": [
            0,
            1,
            2,
            3
          ]
        },
        {
          "id": "piece-2",
          "cells": [
            [
              0,
              0,
              "violet"
            ],
            [
              1,
              0,
              "orange"
            ],
            [
              1,
              1,
              "teal"
            ],
            [
              1,
              2,
              "coral"
            ]
          ],
          "rotation": 1,
          "allowedRotations": [
            0,
            1,
            2,
            3
          ]
        },
        {
          "id": "piece-3",
          "cells": [
            [
              0,
              0,
              "teal"
            ],
            [
              1,
              0,
              "coral"
            ],
            [
              0,
              1,
              "coral"
            ]
          ],
          "rotation": 2,
          "allowedRotations": [
            0,
            1,
            2,
            3
          ]
        },
        {
          "id": "piece-4",
          "cells": [
            [
              1,
              0,
              "orange"
            ],
            [
              0,
              1,
              "orange"
            ],
            [
              1,
              1,
              "teal"
            ],
            [
              0,
              2,
              "teal"
            ]
          ],
          "rotation": 0,
          "allowedRotations": [
            0,
            1,
            2,
            3
          ]
        }
      ]
    },
    {
      "id": "study-10",
      "number": "Study 10",
      "title": "Quiet code",
      "chapter": "Veil",
      "difficulty": "Inference",
      "size": 5,
      "mode": "clues",
      "target": [
        [
          "violet",
          "orange",
          "teal",
          "coral",
          "blue"
        ],
        [
          "orange",
          "teal",
          "coral",
          "blue",
          "lime"
        ],
        [
          "teal",
          "coral",
          "blue",
          "lime",
          "violet"
        ],
        [
          "coral",
          "blue",
          "lime",
          "violet",
          "orange"
        ],
        [
          "blue",
          "lime",
          "violet",
          "orange",
          "teal"
        ]
      ],
      "clues": [
        [
          0,
          0
        ],
        [
          1,
          0
        ],
        [
          4,
          1
        ],
        [
          2,
          2
        ],
        [
          3,
          2
        ],
        [
          0,
          3
        ],
        [
          1,
          3
        ],
        [
          0,
          4
        ],
        [
          4,
          4
        ]
      ],
      "pieces": [
        {
          "id": "piece-4",
          "cells": [
            [
              0,
              0,
              "orange"
            ],
            [
              0,
              1,
              "teal"
            ],
            [
              0,
              2,
              "coral"
            ]
          ],
          "rotation": 0,
          "allowedRotations": [
            0,
            1,
            2,
            3
          ]
        },
        {
          "id": "piece-3",
          "cells": [
            [
              0,
              0,
              "blue"
            ],
            [
              0,
              1,
              "lime"
            ],
            [
              0,
              2,
              "violet"
            ]
          ],
          "rotation": 3,
          "allowedRotations": [
            0,
            1,
            2,
            3
          ]
        },
        {
          "id": "piece-2",
          "cells": [
            [
              0,
              0,
              "teal"
            ],
            [
              1,
              0,
              "coral"
            ],
            [
              1,
              1,
              "blue"
            ]
          ],
          "rotation": 2,
          "allowedRotations": [
            0,
            1,
            2,
            3
          ]
        },
        {
          "id": "piece-1",
          "cells": [
            [
              0,
              0,
              "violet"
            ],
            [
              1,
              0,
              "orange"
            ],
            [
              1,
              1,
              "teal"
            ]
          ],
          "rotation": 1,
          "allowedRotations": [
            0,
            1,
            2,
            3
          ]
        },
        {
          "id": "piece-8",
          "cells": [
            [
              0,
              0,
              "lime"
            ],
            [
              0,
              1,
              "violet"
            ]
          ],
          "rotation": 0,
          "allowedRotations": [
            0,
            1,
            2,
            3
          ]
        },
        {
          "id": "piece-7",
          "cells": [
            [
              1,
              0,
              "blue"
            ],
            [
              0,
              1,
              "blue"
            ],
            [
              1,
              1,
              "lime"
            ]
          ],
          "rotation": 0,
          "allowedRotations": [
            0,
            1,
            2,
            3
          ]
        },
        {
          "id": "piece-6",
          "cells": [
            [
              0,
              0,
              "lime"
            ],
            [
              0,
              1,
              "violet"
            ],
            [
              1,
              1,
              "orange"
            ],
            [
              0,
              2,
              "orange"
            ],
            [
              1,
              2,
              "teal"
            ]
          ],
          "rotation": 0,
          "allowedRotations": [
            0,
            1,
            2,
            3
          ]
        },
        {
          "id": "piece-5",
          "cells": [
            [
              1,
              0,
              "coral"
            ],
            [
              0,
              1,
              "coral"
            ],
            [
              1,
              1,
              "blue"
            ]
          ],
          "rotation": 0,
          "allowedRotations": [
            0,
            1,
            2,
            3
          ]
        }
      ]
    },
    {
      "id": "study-11",
      "number": "Study 11",
      "title": "Broken repeat",
      "chapter": "Veil",
      "difficulty": "Inference",
      "size": 6,
      "mode": "clues",
      "target": [
        [
          "orange",
          "teal",
          "coral",
          "blue",
          "lime",
          "violet"
        ],
        [
          "teal",
          "coral",
          "blue",
          "lime",
          "violet",
          "orange"
        ],
        [
          "coral",
          "blue",
          "lime",
          "violet",
          "orange",
          "teal"
        ],
        [
          "blue",
          "lime",
          "violet",
          "orange",
          "teal",
          "coral"
        ],
        [
          "lime",
          "violet",
          "orange",
          "teal",
          "coral",
          "blue"
        ],
        [
          "violet",
          "orange",
          "teal",
          "coral",
          "blue",
          "lime"
        ]
      ],
      "clues": [
        [
          0,
          0
        ],
        [
          5,
          0
        ],
        [
          3,
          1
        ],
        [
          4,
          1
        ],
        [
          1,
          2
        ],
        [
          2,
          2
        ],
        [
          0,
          3
        ],
        [
          1,
          3
        ],
        [
          5,
          3
        ],
        [
          4,
          4
        ],
        [
          5,
          4
        ],
        [
          2,
          5
        ],
        [
          3,
          5
        ]
      ],
      "pieces": [
        {
          "id": "piece-8",
          "cells": [
            [
              0,
              0,
              "violet"
            ],
            [
              0,
              1,
              "orange"
            ],
            [
              1,
              1,
              "teal"
            ]
          ],
          "rotation": 0,
          "allowedRotations": [
            0,
            1,
            2,
            3
          ]
        },
        {
          "id": "piece-1",
          "cells": [
            [
              0,
              0,
              "orange"
            ],
            [
              1,
              0,
              "teal"
            ],
            [
              2,
              0,
              "coral"
            ],
            [
              3,
              0,
              "blue"
            ],
            [
              1,
              1,
              "coral"
            ],
            [
              2,
              1,
              "blue"
            ],
            [
              3,
              1,
              "lime"
            ]
          ],
          "rotation": 2,
          "allowedRotations": [
            0,
            1,
            2,
            3
          ]
        },
        {
          "id": "piece-2",
          "cells": [
            [
              0,
              0,
              "lime"
            ],
            [
              1,
              0,
              "violet"
            ],
            [
              1,
              1,
              "orange"
            ]
          ],
          "rotation": 3,
          "allowedRotations": [
            0,
            1,
            2,
            3
          ]
        },
        {
          "id": "piece-3",
          "cells": [
            [
              0,
              0,
              "teal"
            ],
            [
              0,
              1,
              "coral"
            ],
            [
              0,
              2,
              "blue"
            ],
            [
              1,
              2,
              "lime"
            ],
            [
              0,
              3,
              "lime"
            ],
            [
              0,
              4,
              "violet"
            ]
          ],
          "rotation": 1,
          "allowedRotations": [
            0,
            1,
            2,
            3
          ]
        },
        {
          "id": "piece-4",
          "cells": [
            [
              0,
              0,
              "violet"
            ],
            [
              0,
              1,
              "orange"
            ],
            [
              0,
              2,
              "teal"
            ],
            [
              0,
              3,
              "coral"
            ]
          ],
          "rotation": 0,
          "allowedRotations": [
            0,
            1,
            2,
            3
          ]
        },
        {
          "id": "piece-5",
          "cells": [
            [
              0,
              0,
              "blue"
            ],
            [
              1,
              0,
              "lime"
            ],
            [
              2,
              0,
              "violet"
            ]
          ],
          "rotation": 0,
          "allowedRotations": [
            0,
            1,
            2,
            3
          ]
        },
        {
          "id": "piece-6",
          "cells": [
            [
              0,
              0,
              "teal"
            ],
            [
              0,
              1,
              "coral"
            ],
            [
              0,
              2,
              "blue"
            ]
          ],
          "rotation": 0,
          "allowedRotations": [
            0,
            1,
            2,
            3
          ]
        },
        {
          "id": "piece-7",
          "cells": [
            [
              0,
              0,
              "violet"
            ],
            [
              1,
              0,
              "orange"
            ],
            [
              0,
              1,
              "orange"
            ],
            [
              1,
              1,
              "teal"
            ],
            [
              1,
              2,
              "coral"
            ],
            [
              2,
              2,
              "blue"
            ],
            [
              3,
              2,
              "lime"
            ]
          ],
          "rotation": 0,
          "allowedRotations": [
            0,
            1,
            2,
            3
          ]
        }
      ]
    },
    {
      "id": "study-12",
      "number": "Study 12",
      "title": "Night index",
      "chapter": "Veil",
      "difficulty": "Inference",
      "size": 6,
      "mode": "clues",
      "target": [
        [
          "teal",
          "coral",
          "blue",
          "lime",
          "violet",
          "orange"
        ],
        [
          "coral",
          "blue",
          "lime",
          "violet",
          "orange",
          "teal"
        ],
        [
          "blue",
          "lime",
          "violet",
          "orange",
          "teal",
          "coral"
        ],
        [
          "lime",
          "violet",
          "orange",
          "teal",
          "coral",
          "blue"
        ],
        [
          "violet",
          "orange",
          "teal",
          "coral",
          "blue",
          "lime"
        ],
        [
          "orange",
          "teal",
          "coral",
          "blue",
          "lime",
          "violet"
        ]
      ],
      "clues": [
        [
          4,
          0
        ],
        [
          5,
          0
        ],
        [
          2,
          1
        ],
        [
          3,
          1
        ],
        [
          0,
          2
        ],
        [
          1,
          2
        ],
        [
          2,
          2
        ],
        [
          0,
          3
        ],
        [
          5,
          3
        ],
        [
          3,
          4
        ],
        [
          4,
          4
        ],
        [
          1,
          5
        ],
        [
          2,
          5
        ]
      ],
      "pieces": [
        {
          "id": "piece-7",
          "cells": [
            [
              1,
              0,
              "violet"
            ],
            [
              0,
              1,
              "violet"
            ],
            [
              1,
              1,
              "orange"
            ],
            [
              0,
              2,
              "orange"
            ]
          ],
          "rotation": 0,
          "allowedRotations": [
            0,
            1,
            2,
            3
          ]
        },
        {
          "id": "piece-6",
          "cells": [
            [
              1,
              0,
              "coral"
            ],
            [
              0,
              1,
              "coral"
            ],
            [
              1,
              1,
              "blue"
            ],
            [
              0,
              2,
              "blue"
            ],
            [
              0,
              3,
              "lime"
            ]
          ],
          "rotation": 0,
          "allowedRotations": [
            0,
            1,
            2,
            3
          ]
        },
        {
          "id": "piece-5",
          "cells": [
            [
              1,
              0,
              "orange"
            ],
            [
              2,
              0,
              "teal"
            ],
            [
              0,
              1,
              "orange"
            ],
            [
              1,
              1,
              "teal"
            ]
          ],
          "rotation": 0,
          "allowedRotations": [
            0,
            1,
            2,
            3
          ]
        },
        {
          "id": "piece-4",
          "cells": [
            [
              0,
              0,
              "coral"
            ],
            [
              0,
              1,
              "blue"
            ],
            [
              1,
              1,
              "lime"
            ],
            [
              2,
              1,
              "violet"
            ],
            [
              0,
              2,
              "lime"
            ]
          ],
          "rotation": 0,
          "allowedRotations": [
            0,
            1,
            2,
            3
          ]
        },
        {
          "id": "piece-3",
          "cells": [
            [
              0,
              0,
              "violet"
            ],
            [
              1,
              0,
              "orange"
            ]
          ],
          "rotation": 2,
          "allowedRotations": [
            0,
            1,
            2,
            3
          ]
        },
        {
          "id": "piece-2",
          "cells": [
            [
              0,
              0,
              "blue"
            ],
            [
              1,
              0,
              "lime"
            ],
            [
              0,
              1,
              "lime"
            ],
            [
              1,
              1,
              "violet"
            ],
            [
              2,
              1,
              "orange"
            ],
            [
              3,
              1,
              "teal"
            ]
          ],
          "rotation": 1,
          "allowedRotations": [
            0,
            1,
            2,
            3
          ]
        },
        {
          "id": "piece-1",
          "cells": [
            [
              0,
              0,
              "teal"
            ],
            [
              1,
              0,
              "coral"
            ],
            [
              1,
              1,
              "blue"
            ]
          ],
          "rotation": 3,
          "allowedRotations": [
            0,
            1,
            2,
            3
          ]
        },
        {
          "id": "piece-9",
          "cells": [
            [
              0,
              0,
              "lime"
            ],
            [
              0,
              1,
              "violet"
            ]
          ],
          "rotation": 0,
          "allowedRotations": [
            0,
            1,
            2,
            3
          ]
        },
        {
          "id": "piece-8",
          "cells": [
            [
              1,
              0,
              "teal"
            ],
            [
              2,
              0,
              "coral"
            ],
            [
              0,
              1,
              "teal"
            ],
            [
              1,
              1,
              "coral"
            ],
            [
              2,
              1,
              "blue"
            ]
          ],
          "rotation": 0,
          "allowedRotations": [
            0,
            1,
            2,
            3
          ]
        }
      ]
    },
    {
      "id": "study-13",
      "number": "Study 13",
      "title": "Afterimage",
      "chapter": "Deep field",
      "difficulty": "Deep",
      "size": 6,
      "mode": "clues",
      "target": [
        [
          "teal",
          "teal",
          "teal",
          "teal",
          "teal",
          "teal"
        ],
        [
          "teal",
          "teal",
          "teal",
          "teal",
          "teal",
          "blue"
        ],
        [
          "teal",
          "teal",
          "teal",
          "teal",
          "blue",
          "violet"
        ],
        [
          "teal",
          "teal",
          "teal",
          "blue",
          "violet",
          "teal"
        ],
        [
          "teal",
          "teal",
          "blue",
          "violet",
          "teal",
          "blue"
        ],
        [
          "teal",
          "blue",
          "violet",
          "teal",
          "blue",
          "violet"
        ]
      ],
      "clues": [
        [
          3,
          0
        ],
        [
          1,
          1
        ],
        [
          2,
          1
        ],
        [
          0,
          2
        ],
        [
          4,
          3
        ],
        [
          2,
          4
        ],
        [
          3,
          4
        ],
        [
          0,
          5
        ],
        [
          1,
          5
        ]
      ],
      "pieces": [
        {
          "id": "piece-6",
          "cells": [
            [
              0,
              0,
              "teal"
            ],
            [
              0,
              1,
              "teal"
            ],
            [
              0,
              2,
              "teal"
            ]
          ],
          "rotation": 0,
          "allowedRotations": [
            0,
            1,
            2,
            3
          ]
        },
        {
          "id": "piece-7",
          "cells": [
            [
              0,
              0,
              "violet"
            ],
            [
              0,
              1,
              "teal"
            ],
            [
              0,
              2,
              "blue"
            ]
          ],
          "rotation": 0,
          "allowedRotations": [
            0,
            1,
            2,
            3
          ]
        },
        {
          "id": "piece-8",
          "cells": [
            [
              0,
              0,
              "teal"
            ],
            [
              0,
              1,
              "blue"
            ],
            [
              1,
              1,
              "violet"
            ]
          ],
          "rotation": 0,
          "allowedRotations": [
            0,
            1,
            2,
            3
          ]
        },
        {
          "id": "piece-1",
          "cells": [
            [
              0,
              0,
              "teal"
            ],
            [
              1,
              0,
              "teal"
            ],
            [
              2,
              0,
              "teal"
            ],
            [
              3,
              0,
              "teal"
            ],
            [
              0,
              1,
              "teal"
            ]
          ],
          "rotation": 1,
          "allowedRotations": [
            0,
            1,
            2,
            3
          ]
        },
        {
          "id": "piece-2",
          "cells": [
            [
              1,
              0,
              "teal"
            ],
            [
              2,
              0,
              "teal"
            ],
            [
              1,
              1,
              "teal"
            ],
            [
              0,
              2,
              "teal"
            ],
            [
              1,
              2,
              "blue"
            ],
            [
              0,
              3,
              "blue"
            ]
          ],
          "rotation": 2,
          "allowedRotations": [
            0,
            1,
            2,
            3
          ]
        },
        {
          "id": "piece-3",
          "cells": [
            [
              1,
              0,
              "teal"
            ],
            [
              0,
              1,
              "teal"
            ],
            [
              1,
              1,
              "teal"
            ],
            [
              1,
              2,
              "teal"
            ]
          ],
          "rotation": 3,
          "allowedRotations": [
            0,
            1,
            2,
            3
          ]
        },
        {
          "id": "piece-4",
          "cells": [
            [
              0,
              0,
              "teal"
            ],
            [
              1,
              0,
              "teal"
            ],
            [
              0,
              1,
              "teal"
            ],
            [
              0,
              2,
              "teal"
            ],
            [
              0,
              3,
              "blue"
            ],
            [
              1,
              3,
              "violet"
            ],
            [
              1,
              4,
              "teal"
            ]
          ],
          "rotation": 1,
          "allowedRotations": [
            0,
            1,
            2,
            3
          ]
        },
        {
          "id": "piece-5",
          "cells": [
            [
              0,
              0,
              "blue"
            ],
            [
              0,
              1,
              "violet"
            ],
            [
              0,
              2,
              "teal"
            ],
            [
              0,
              3,
              "blue"
            ],
            [
              0,
              4,
              "violet"
            ]
          ],
          "rotation": 0,
          "allowedRotations": [
            0,
            1,
            2,
            3
          ]
        }
      ]
    },
    {
      "id": "study-14",
      "number": "Study 14",
      "title": "Hidden current",
      "chapter": "Deep field",
      "difficulty": "Deep",
      "size": 6,
      "mode": "clues",
      "target": [
        [
          "coral",
          "coral",
          "coral",
          "coral",
          "coral",
          "coral"
        ],
        [
          "coral",
          "coral",
          "coral",
          "coral",
          "coral",
          "lime"
        ],
        [
          "coral",
          "coral",
          "coral",
          "coral",
          "lime",
          "orange"
        ],
        [
          "coral",
          "coral",
          "coral",
          "lime",
          "orange",
          "coral"
        ],
        [
          "coral",
          "coral",
          "lime",
          "orange",
          "coral",
          "lime"
        ],
        [
          "coral",
          "lime",
          "orange",
          "coral",
          "lime",
          "orange"
        ]
      ],
      "clues": [
        [
          2,
          0
        ],
        [
          3,
          0
        ],
        [
          1,
          1
        ],
        [
          5,
          2
        ],
        [
          3,
          3
        ],
        [
          1,
          4
        ],
        [
          2,
          4
        ],
        [
          0,
          5
        ]
      ],
      "pieces": [
        {
          "id": "piece-4",
          "cells": [
            [
              0,
              0,
              "coral"
            ],
            [
              0,
              1,
              "coral"
            ],
            [
              1,
              1,
              "coral"
            ],
            [
              2,
              1,
              "coral"
            ],
            [
              0,
              2,
              "coral"
            ]
          ],
          "rotation": 2,
          "allowedRotations": [
            0,
            1,
            2,
            3
          ]
        },
        {
          "id": "piece-3",
          "cells": [
            [
              1,
              0,
              "coral"
            ],
            [
              0,
              1,
              "coral"
            ],
            [
              1,
              1,
              "lime"
            ],
            [
              0,
              2,
              "lime"
            ],
            [
              1,
              2,
              "orange"
            ]
          ],
          "rotation": 1,
          "allowedRotations": [
            0,
            1,
            2,
            3
          ]
        },
        {
          "id": "piece-2",
          "cells": [
            [
              0,
              0,
              "coral"
            ],
            [
              1,
              0,
              "coral"
            ],
            [
              2,
              0,
              "coral"
            ],
            [
              1,
              1,
              "coral"
            ]
          ],
          "rotation": 3,
          "allowedRotations": [
            0,
            1,
            2,
            3
          ]
        },
        {
          "id": "piece-1",
          "cells": [
            [
              0,
              0,
              "coral"
            ],
            [
              1,
              0,
              "coral"
            ],
            [
              0,
              1,
              "coral"
            ],
            [
              1,
              1,
              "coral"
            ],
            [
              2,
              1,
              "coral"
            ]
          ],
          "rotation": 2,
          "allowedRotations": [
            0,
            1,
            2,
            3
          ]
        },
        {
          "id": "piece-9",
          "cells": [
            [
              0,
              0,
              "coral"
            ],
            [
              1,
              0,
              "lime"
            ]
          ],
          "rotation": 0,
          "allowedRotations": [
            0,
            1,
            2,
            3
          ]
        },
        {
          "id": "piece-8",
          "cells": [
            [
              2,
              0,
              "coral"
            ],
            [
              0,
              1,
              "orange"
            ],
            [
              1,
              1,
              "coral"
            ],
            [
              2,
              1,
              "lime"
            ],
            [
              3,
              1,
              "orange"
            ]
          ],
          "rotation": 0,
          "allowedRotations": [
            0,
            1,
            2,
            3
          ]
        },
        {
          "id": "piece-7",
          "cells": [
            [
              0,
              0,
              "coral"
            ],
            [
              1,
              0,
              "lime"
            ],
            [
              2,
              0,
              "orange"
            ]
          ],
          "rotation": 0,
          "allowedRotations": [
            0,
            1,
            2,
            3
          ]
        },
        {
          "id": "piece-6",
          "cells": [
            [
              0,
              0,
              "lime"
            ],
            [
              1,
              0,
              "orange"
            ],
            [
              2,
              0,
              "coral"
            ],
            [
              2,
              1,
              "lime"
            ]
          ],
          "rotation": 0,
          "allowedRotations": [
            0,
            1,
            2,
            3
          ]
        },
        {
          "id": "piece-5",
          "cells": [
            [
              0,
              0,
              "coral"
            ],
            [
              1,
              0,
              "coral"
            ],
            [
              2,
              0,
              "coral"
            ]
          ],
          "rotation": 0,
          "allowedRotations": [
            0,
            1,
            2,
            3
          ]
        }
      ]
    },
    {
      "id": "study-15",
      "number": "Study 15",
      "title": "Long memory",
      "chapter": "Deep field",
      "difficulty": "Deep",
      "size": 7,
      "mode": "clues",
      "target": [
        [
          "lime",
          "lime",
          "lime",
          "lime",
          "lime",
          "lime",
          "lime"
        ],
        [
          "lime",
          "lime",
          "lime",
          "lime",
          "lime",
          "lime",
          "orange"
        ],
        [
          "lime",
          "lime",
          "lime",
          "lime",
          "lime",
          "orange",
          "coral"
        ],
        [
          "lime",
          "lime",
          "lime",
          "lime",
          "orange",
          "coral",
          "lime"
        ],
        [
          "lime",
          "lime",
          "lime",
          "orange",
          "coral",
          "lime",
          "orange"
        ],
        [
          "lime",
          "lime",
          "orange",
          "coral",
          "lime",
          "orange",
          "coral"
        ],
        [
          "lime",
          "orange",
          "coral",
          "lime",
          "orange",
          "coral",
          "lime"
        ]
      ],
      "clues": [
        [
          2,
          0
        ],
        [
          0,
          1
        ],
        [
          6,
          1
        ],
        [
          4,
          2
        ],
        [
          2,
          3
        ],
        [
          3,
          3
        ],
        [
          1,
          4
        ],
        [
          6,
          4
        ],
        [
          5,
          5
        ],
        [
          3,
          6
        ]
      ],
      "pieces": [
        {
          "id": "piece-4",
          "cells": [
            [
              1,
              0,
              "lime"
            ],
            [
              5,
              0,
              "orange"
            ],
            [
              0,
              1,
              "lime"
            ],
            [
              1,
              1,
              "lime"
            ],
            [
              2,
              1,
              "lime"
            ],
            [
              3,
              1,
              "lime"
            ],
            [
              4,
              1,
              "orange"
            ],
            [
              5,
              1,
              "coral"
            ],
            [
              0,
              2,
              "lime"
            ]
          ],
          "rotation": 3,
          "allowedRotations": [
            0,
            1,
            2,
            3
          ]
        },
        {
          "id": "piece-5",
          "cells": [
            [
              0,
              0,
              "lime"
            ],
            [
              1,
              0,
              "lime"
            ],
            [
              0,
              1,
              "lime"
            ]
          ],
          "rotation": 0,
          "allowedRotations": [
            0,
            1,
            2,
            3
          ]
        },
        {
          "id": "piece-6",
          "cells": [
            [
              1,
              0,
              "orange"
            ],
            [
              2,
              0,
              "coral"
            ],
            [
              0,
              1,
              "orange"
            ],
            [
              1,
              1,
              "coral"
            ],
            [
              2,
              1,
              "lime"
            ],
            [
              0,
              2,
              "coral"
            ],
            [
              1,
              2,
              "lime"
            ],
            [
              2,
              2,
              "orange"
            ]
          ],
          "rotation": 0,
          "allowedRotations": [
            0,
            1,
            2,
            3
          ]
        },
        {
          "id": "piece-7",
          "cells": [
            [
              0,
              0,
              "lime"
            ],
            [
              0,
              1,
              "lime"
            ],
            [
              1,
              1,
              "orange"
            ]
          ],
          "rotation": 0,
          "allowedRotations": [
            0,
            1,
            2,
            3
          ]
        },
        {
          "id": "piece-8",
          "cells": [
            [
              0,
              0,
              "orange"
            ],
            [
              1,
              0,
              "coral"
            ],
            [
              0,
              1,
              "coral"
            ],
            [
              1,
              1,
              "lime"
            ]
          ],
          "rotation": 0,
          "allowedRotations": [
            0,
            1,
            2,
            3
          ]
        },
        {
          "id": "piece-1",
          "cells": [
            [
              0,
              0,
              "lime"
            ],
            [
              1,
              0,
              "lime"
            ],
            [
              0,
              1,
              "lime"
            ],
            [
              1,
              1,
              "lime"
            ],
            [
              0,
              2,
              "lime"
            ]
          ],
          "rotation": 3,
          "allowedRotations": [
            0,
            1,
            2,
            3
          ]
        },
        {
          "id": "piece-2",
          "cells": [
            [
              0,
              0,
              "lime"
            ],
            [
              1,
              0,
              "lime"
            ],
            [
              0,
              1,
              "lime"
            ],
            [
              1,
              1,
              "lime"
            ],
            [
              2,
              1,
              "lime"
            ],
            [
              0,
              2,
              "lime"
            ],
            [
              1,
              2,
              "lime"
            ],
            [
              2,
              2,
              "lime"
            ]
          ],
          "rotation": 1,
          "allowedRotations": [
            0,
            1,
            2,
            3
          ]
        },
        {
          "id": "piece-3",
          "cells": [
            [
              0,
              0,
              "lime"
            ],
            [
              1,
              0,
              "lime"
            ],
            [
              2,
              0,
              "lime"
            ],
            [
              1,
              1,
              "lime"
            ],
            [
              2,
              1,
              "orange"
            ],
            [
              2,
              2,
              "coral"
            ],
            [
              2,
              3,
              "lime"
            ],
            [
              1,
              4,
              "lime"
            ],
            [
              2,
              4,
              "orange"
            ]
          ],
          "rotation": 2,
          "allowedRotations": [
            0,
            1,
            2,
            3
          ]
        }
      ]
    },
    {
      "id": "study-16",
      "number": "Study 16",
      "title": "Atlas complete",
      "chapter": "Deep field",
      "difficulty": "Deep",
      "size": 7,
      "mode": "clues",
      "target": [
        [
          "violet",
          "violet",
          "violet",
          "violet",
          "violet",
          "violet",
          "violet"
        ],
        [
          "violet",
          "violet",
          "violet",
          "violet",
          "violet",
          "violet",
          "teal"
        ],
        [
          "violet",
          "violet",
          "violet",
          "violet",
          "violet",
          "teal",
          "blue"
        ],
        [
          "violet",
          "violet",
          "violet",
          "violet",
          "teal",
          "blue",
          "violet"
        ],
        [
          "violet",
          "violet",
          "violet",
          "teal",
          "blue",
          "violet",
          "teal"
        ],
        [
          "violet",
          "violet",
          "teal",
          "blue",
          "violet",
          "teal",
          "blue"
        ],
        [
          "violet",
          "teal",
          "blue",
          "violet",
          "teal",
          "blue",
          "violet"
        ]
      ],
      "clues": [
        [
          1,
          0
        ],
        [
          5,
          1
        ],
        [
          3,
          2
        ],
        [
          4,
          2
        ],
        [
          2,
          3
        ],
        [
          0,
          4
        ],
        [
          6,
          4
        ],
        [
          4,
          5
        ],
        [
          2,
          6
        ],
        [
          3,
          6
        ]
      ],
      "pieces": [
        {
          "id": "piece-1",
          "cells": [
            [
              0,
              0,
              "violet"
            ],
            [
              1,
              0,
              "violet"
            ],
            [
              2,
              0,
              "violet"
            ],
            [
              0,
              1,
              "violet"
            ],
            [
              1,
              1,
              "violet"
            ],
            [
              0,
              2,
              "violet"
            ],
            [
              1,
              2,
              "violet"
            ],
            [
              0,
              3,
              "violet"
            ]
          ],
          "rotation": 1,
          "allowedRotations": [
            0,
            1,
            2,
            3
          ]
        },
        {
          "id": "piece-9",
          "cells": [
            [
              1,
              0,
              "blue"
            ],
            [
              0,
              1,
              "blue"
            ],
            [
              1,
              1,
              "violet"
            ]
          ],
          "rotation": 0,
          "allowedRotations": [
            0,
            1,
            2,
            3
          ]
        },
        {
          "id": "piece-8",
          "cells": [
            [
              0,
              0,
              "teal"
            ],
            [
              1,
              0,
              "blue"
            ]
          ],
          "rotation": 0,
          "allowedRotations": [
            0,
            1,
            2,
            3
          ]
        },
        {
          "id": "piece-7",
          "cells": [
            [
              4,
              0,
              "blue"
            ],
            [
              0,
              1,
              "violet"
            ],
            [
              4,
              1,
              "violet"
            ],
            [
              0,
              2,
              "violet"
            ],
            [
              1,
              2,
              "teal"
            ],
            [
              2,
              2,
              "blue"
            ],
            [
              3,
              2,
              "violet"
            ],
            [
              4,
              2,
              "teal"
            ]
          ],
          "rotation": 0,
          "allowedRotations": [
            0,
            1,
            2,
            3
          ]
        },
        {
          "id": "piece-6",
          "cells": [
            [
              1,
              0,
              "violet"
            ],
            [
              2,
              0,
              "violet"
            ],
            [
              0,
              1,
              "violet"
            ],
            [
              1,
              1,
              "violet"
            ],
            [
              2,
              1,
              "violet"
            ],
            [
              3,
              1,
              "teal"
            ],
            [
              1,
              2,
              "violet"
            ]
          ],
          "rotation": 0,
          "allowedRotations": [
            0,
            1,
            2,
            3
          ]
        },
        {
          "id": "piece-5",
          "cells": [
            [
              0,
              0,
              "teal"
            ],
            [
              0,
              1,
              "blue"
            ],
            [
              0,
              2,
              "violet"
            ],
            [
              0,
              3,
              "teal"
            ]
          ],
          "rotation": 0,
          "allowedRotations": [
            0,
            1,
            2,
            3
          ]
        },
        {
          "id": "piece-4",
          "cells": [
            [
              0,
              0,
              "violet"
            ],
            [
              0,
              1,
              "teal"
            ],
            [
              0,
              2,
              "blue"
            ],
            [
              0,
              3,
              "violet"
            ],
            [
              0,
              4,
              "teal"
            ]
          ],
          "rotation": 1,
          "allowedRotations": [
            0,
            1,
            2,
            3
          ]
        },
        {
          "id": "piece-3",
          "cells": [
            [
              2,
              0,
              "violet"
            ],
            [
              1,
              1,
              "violet"
            ],
            [
              2,
              1,
              "violet"
            ],
            [
              1,
              2,
              "violet"
            ],
            [
              0,
              3,
              "violet"
            ],
            [
              1,
              3,
              "teal"
            ]
          ],
          "rotation": 3,
          "allowedRotations": [
            0,
            1,
            2,
            3
          ]
        },
        {
          "id": "piece-2",
          "cells": [
            [
              1,
              0,
              "violet"
            ],
            [
              2,
              0,
              "violet"
            ],
            [
              0,
              1,
              "violet"
            ],
            [
              1,
              1,
              "violet"
            ],
            [
              0,
              2,
              "violet"
            ],
            [
              1,
              2,
              "violet"
            ]
          ],
          "rotation": 2,
          "allowedRotations": [
            0,
            1,
            2,
            3
          ]
        }
      ]
    },
    {
      "id": "study-17",
      "number": "Study 17",
      "title": "Drift map",
      "chapter": "Echoes",
      "difficulty": "Focus",
      "size": 5,
      "mode": "target",
      "target": [
        [
          "coral",
          "lime",
          "violet",
          "orange",
          "teal"
        ],
        [
          "lime",
          "violet",
          "orange",
          "teal",
          "coral"
        ],
        [
          "violet",
          "orange",
          "teal",
          "coral",
          "lime"
        ],
        [
          "orange",
          "teal",
          "coral",
          "lime",
          "violet"
        ],
        [
          "teal",
          "coral",
          "lime",
          "violet",
          "orange"
        ]
      ],
      "pieces": [
        {
          "id": "piece-1",
          "cells": [
            [
              0,
              0,
              "coral"
            ],
            [
              1,
              0,
              "lime"
            ],
            [
              0,
              1,
              "lime"
            ],
            [
              1,
              1,
              "violet"
            ],
            [
              0,
              2,
              "violet"
            ]
          ],
          "rotation": 3,
          "allowedRotations": [
            0,
            1,
            2,
            3
          ]
        },
        {
          "id": "piece-2",
          "cells": [
            [
              0,
              0,
              "violet"
            ],
            [
              1,
              0,
              "orange"
            ],
            [
              2,
              0,
              "teal"
            ],
            [
              0,
              1,
              "orange"
            ],
            [
              1,
              1,
              "teal"
            ]
          ],
          "rotation": 3,
          "allowedRotations": [
            0,
            1,
            2,
            3
          ]
        },
        {
          "id": "piece-3",
          "cells": [
            [
              3,
              0,
              "coral"
            ],
            [
              0,
              1,
              "orange"
            ],
            [
              1,
              1,
              "teal"
            ],
            [
              2,
              1,
              "coral"
            ],
            [
              3,
              1,
              "lime"
            ]
          ],
          "rotation": 3,
          "allowedRotations": [
            0,
            1,
            2,
            3
          ]
        },
        {
          "id": "piece-4",
          "cells": [
            [
              0,
              0,
              "orange"
            ],
            [
              1,
              0,
              "teal"
            ],
            [
              0,
              1,
              "teal"
            ],
            [
              1,
              1,
              "coral"
            ],
            [
              2,
              1,
              "lime"
            ]
          ],
          "rotation": 2,
          "allowedRotations": [
            0,
            1,
            2,
            3
          ]
        },
        {
          "id": "piece-5",
          "cells": [
            [
              0,
              0,
              "coral"
            ],
            [
              1,
              0,
              "lime"
            ],
            [
              2,
              0,
              "violet"
            ],
            [
              1,
              1,
              "violet"
            ],
            [
              2,
              1,
              "orange"
            ]
          ],
          "rotation": 0,
          "allowedRotations": [
            0,
            1,
            2,
            3
          ]
        }
      ]
    },
    {
      "id": "study-18",
      "number": "Study 18",
      "title": "Slow return",
      "chapter": "Echoes",
      "difficulty": "Turn",
      "size": 5,
      "mode": "clues",
      "target": [
        [
          "blue",
          "violet",
          "teal",
          "blue",
          "violet"
        ],
        [
          "violet",
          "teal",
          "blue",
          "violet",
          "teal"
        ],
        [
          "teal",
          "blue",
          "violet",
          "teal",
          "blue"
        ],
        [
          "blue",
          "violet",
          "teal",
          "blue",
          "violet"
        ],
        [
          "violet",
          "teal",
          "blue",
          "violet",
          "teal"
        ]
      ],
      "clues": [
        [
          2,
          0
        ],
        [
          0,
          1
        ],
        [
          3,
          1
        ],
        [
          0,
          2
        ],
        [
          1,
          2
        ],
        [
          2,
          2
        ],
        [
          0,
          4
        ],
        [
          2,
          4
        ],
        [
          3,
          4
        ]
      ],
      "pieces": [
        {
          "id": "piece-1",
          "cells": [
            [
              0,
              0,
              "blue"
            ],
            [
              1,
              0,
              "violet"
            ],
            [
              0,
              1,
              "violet"
            ],
            [
              1,
              1,
              "teal"
            ]
          ],
          "rotation": 3,
          "allowedRotations": [
            0,
            1,
            2,
            3
          ]
        },
        {
          "id": "piece-2",
          "cells": [
            [
              0,
              0,
              "teal"
            ],
            [
              1,
              0,
              "blue"
            ],
            [
              2,
              0,
              "violet"
            ],
            [
              0,
              1,
              "blue"
            ]
          ],
          "rotation": 1,
          "allowedRotations": [
            0,
            1,
            2,
            3
          ]
        },
        {
          "id": "piece-3",
          "cells": [
            [
              0,
              0,
              "violet"
            ],
            [
              1,
              0,
              "teal"
            ],
            [
              0,
              1,
              "teal"
            ],
            [
              1,
              1,
              "blue"
            ]
          ],
          "rotation": 2,
          "allowedRotations": [
            0,
            1,
            2,
            3
          ]
        },
        {
          "id": "piece-4",
          "cells": [
            [
              0,
              0,
              "teal"
            ],
            [
              1,
              0,
              "blue"
            ],
            [
              0,
              1,
              "blue"
            ],
            [
              1,
              1,
              "violet"
            ]
          ],
          "rotation": 0,
          "allowedRotations": [
            0,
            1,
            2,
            3
          ]
        },
        {
          "id": "piece-5",
          "cells": [
            [
              0,
              0,
              "violet"
            ],
            [
              0,
              1,
              "teal"
            ],
            [
              1,
              1,
              "blue"
            ],
            [
              2,
              1,
              "violet"
            ]
          ],
          "rotation": 3,
          "allowedRotations": [
            0,
            1,
            2,
            3
          ]
        },
        {
          "id": "piece-6",
          "cells": [
            [
              0,
              0,
              "violet"
            ],
            [
              1,
              0,
              "teal"
            ],
            [
              2,
              0,
              "blue"
            ],
            [
              3,
              0,
              "violet"
            ],
            [
              4,
              0,
              "teal"
            ]
          ],
          "rotation": 1,
          "allowedRotations": [
            0,
            1,
            2,
            3
          ]
        }
      ]
    },
    {
      "id": "study-19",
      "number": "Study 19",
      "title": "Wide awake",
      "chapter": "Echoes",
      "difficulty": "Inference",
      "size": 6,
      "mode": "target",
      "target": [
        [
          "coral",
          "lime",
          "violet",
          "orange",
          "teal",
          "blue"
        ],
        [
          "lime",
          "violet",
          "orange",
          "teal",
          "blue",
          "coral"
        ],
        [
          "violet",
          "orange",
          "teal",
          "blue",
          "coral",
          "lime"
        ],
        [
          "orange",
          "teal",
          "blue",
          "coral",
          "lime",
          "violet"
        ],
        [
          "teal",
          "blue",
          "coral",
          "lime",
          "violet",
          "orange"
        ],
        [
          "blue",
          "coral",
          "lime",
          "violet",
          "orange",
          "teal"
        ]
      ],
      "pieces": [
        {
          "id": "piece-1",
          "cells": [
            [
              0,
              0,
              "coral"
            ],
            [
              1,
              0,
              "lime"
            ],
            [
              0,
              1,
              "lime"
            ],
            [
              1,
              1,
              "violet"
            ],
            [
              0,
              2,
              "violet"
            ],
            [
              1,
              2,
              "orange"
            ]
          ],
          "rotation": 1,
          "allowedRotations": [
            0,
            1,
            2,
            3
          ]
        },
        {
          "id": "piece-2",
          "cells": [
            [
              0,
              0,
              "violet"
            ],
            [
              1,
              0,
              "orange"
            ],
            [
              2,
              0,
              "teal"
            ],
            [
              3,
              0,
              "blue"
            ],
            [
              0,
              1,
              "orange"
            ],
            [
              1,
              1,
              "teal"
            ]
          ],
          "rotation": 1,
          "allowedRotations": [
            0,
            1,
            2,
            3
          ]
        },
        {
          "id": "piece-3",
          "cells": [
            [
              0,
              0,
              "blue"
            ],
            [
              1,
              0,
              "coral"
            ],
            [
              0,
              1,
              "coral"
            ],
            [
              1,
              1,
              "lime"
            ],
            [
              0,
              2,
              "lime"
            ],
            [
              1,
              2,
              "violet"
            ]
          ],
          "rotation": 0,
          "allowedRotations": [
            0,
            1,
            2,
            3
          ]
        },
        {
          "id": "piece-4",
          "cells": [
            [
              0,
              0,
              "teal"
            ],
            [
              1,
              0,
              "blue"
            ],
            [
              0,
              1,
              "blue"
            ],
            [
              1,
              1,
              "coral"
            ],
            [
              0,
              2,
              "coral"
            ],
            [
              1,
              2,
              "lime"
            ]
          ],
          "rotation": 0,
          "allowedRotations": [
            0,
            1,
            2,
            3
          ]
        },
        {
          "id": "piece-5",
          "cells": [
            [
              0,
              0,
              "orange"
            ],
            [
              1,
              0,
              "teal"
            ],
            [
              0,
              1,
              "teal"
            ],
            [
              1,
              1,
              "blue"
            ],
            [
              0,
              2,
              "blue"
            ],
            [
              1,
              2,
              "coral"
            ]
          ],
          "rotation": 1,
          "allowedRotations": [
            0,
            1,
            2,
            3
          ]
        },
        {
          "id": "piece-6",
          "cells": [
            [
              2,
              0,
              "violet"
            ],
            [
              3,
              0,
              "orange"
            ],
            [
              0,
              1,
              "lime"
            ],
            [
              1,
              1,
              "violet"
            ],
            [
              2,
              1,
              "orange"
            ],
            [
              3,
              1,
              "teal"
            ]
          ],
          "rotation": 0,
          "allowedRotations": [
            0,
            1,
            2,
            3
          ]
        }
      ]
    },
    {
      "id": "study-20",
      "number": "Study 20",
      "title": "Still center",
      "chapter": "Echoes",
      "difficulty": "Deep",
      "size": 6,
      "mode": "clues",
      "target": [
        [
          "teal",
          "teal",
          "teal",
          "teal",
          "teal",
          "teal"
        ],
        [
          "teal",
          "coral",
          "coral",
          "coral",
          "coral",
          "teal"
        ],
        [
          "teal",
          "coral",
          "lime",
          "lime",
          "coral",
          "teal"
        ],
        [
          "teal",
          "coral",
          "lime",
          "lime",
          "coral",
          "teal"
        ],
        [
          "teal",
          "coral",
          "coral",
          "coral",
          "coral",
          "teal"
        ],
        [
          "teal",
          "teal",
          "teal",
          "teal",
          "teal",
          "teal"
        ]
      ],
      "clues": [
        [
          0,
          0
        ],
        [
          2,
          0
        ],
        [
          5,
          0
        ],
        [
          4,
          1
        ],
        [
          1,
          2
        ],
        [
          2,
          2
        ],
        [
          1,
          4
        ],
        [
          2,
          4
        ],
        [
          3,
          4
        ],
        [
          4,
          4
        ],
        [
          3,
          5
        ],
        [
          5,
          5
        ]
      ],
      "pieces": [
        {
          "id": "piece-1",
          "cells": [
            [
              0,
              0,
              "teal"
            ],
            [
              1,
              0,
              "teal"
            ],
            [
              2,
              0,
              "teal"
            ],
            [
              3,
              0,
              "teal"
            ],
            [
              4,
              0,
              "teal"
            ],
            [
              5,
              0,
              "teal"
            ]
          ],
          "rotation": 1,
          "allowedRotations": [
            0,
            1,
            2,
            3
          ]
        },
        {
          "id": "piece-2",
          "cells": [
            [
              0,
              0,
              "teal"
            ],
            [
              0,
              1,
              "teal"
            ],
            [
              0,
              2,
              "teal"
            ],
            [
              0,
              3,
              "teal"
            ],
            [
              0,
              4,
              "teal"
            ]
          ],
          "rotation": 2,
          "allowedRotations": [
            0,
            1,
            2,
            3
          ]
        },
        {
          "id": "piece-3",
          "cells": [
            [
              0,
              0,
              "teal"
            ],
            [
              0,
              1,
              "teal"
            ],
            [
              0,
              2,
              "teal"
            ],
            [
              0,
              3,
              "teal"
            ],
            [
              0,
              4,
              "teal"
            ]
          ],
          "rotation": 3,
          "allowedRotations": [
            0,
            1,
            2,
            3
          ]
        },
        {
          "id": "piece-4",
          "cells": [
            [
              0,
              0,
              "teal"
            ],
            [
              1,
              0,
              "teal"
            ],
            [
              2,
              0,
              "teal"
            ],
            [
              3,
              0,
              "teal"
            ]
          ],
          "rotation": 2,
          "allowedRotations": [
            0,
            1,
            2,
            3
          ]
        },
        {
          "id": "piece-5",
          "cells": [
            [
              0,
              0,
              "coral"
            ],
            [
              1,
              0,
              "coral"
            ],
            [
              2,
              0,
              "coral"
            ],
            [
              3,
              0,
              "coral"
            ],
            [
              0,
              1,
              "coral"
            ],
            [
              0,
              2,
              "coral"
            ]
          ],
          "rotation": 3,
          "allowedRotations": [
            0,
            1,
            2,
            3
          ]
        },
        {
          "id": "piece-6",
          "cells": [
            [
              3,
              0,
              "coral"
            ],
            [
              3,
              1,
              "coral"
            ],
            [
              0,
              2,
              "coral"
            ],
            [
              1,
              2,
              "coral"
            ],
            [
              2,
              2,
              "coral"
            ],
            [
              3,
              2,
              "coral"
            ]
          ],
          "rotation": 0,
          "allowedRotations": [
            0,
            1,
            2,
            3
          ]
        },
        {
          "id": "piece-7",
          "cells": [
            [
              0,
              0,
              "lime"
            ],
            [
              0,
              1,
              "lime"
            ]
          ],
          "rotation": 2,
          "allowedRotations": [
            0,
            1,
            2,
            3
          ]
        },
        {
          "id": "piece-8",
          "cells": [
            [
              0,
              0,
              "lime"
            ],
            [
              0,
              1,
              "lime"
            ]
          ],
          "rotation": 0,
          "allowedRotations": [
            0,
            1,
            2,
            3
          ]
        }
      ]
    }
  ]
};
